name: "Test Action"
# Description must be less than 125 characters.
description: "Test Action"
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  multi:
    description: "Multi Shit"
  token:
    description: "Token"
    default: ${{ github.token }}

outputs:
  results:
    description: "Results"

runs:
  using: "node20"
  main: "dist/index.js"
